// eShop.js (fully updated)    
    
// Wait for DOM to load document.addEventListener("DOMContentLoaded", () => { // === 1. Home Redirection === document.getElementById("homeBtn").addEventListener("click", () => { window.location.href = "home.html"; });    
    
// === 2. Location Detection === const locationDisplay = document.getElementById("locationDisplay"); document.getElementById("locationBtn").addEventListener("click", () => { if (navigator.geolocation) { navigator.geolocation.getCurrentPosition(async (position) => { const { latitude, longitude } = position.coords; localStorage.setItem("user_coords", JSON.stringify({ latitude, longitude })); try { const url = https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}; const response = await fetch(url); const data = await response.json(); const locationName = data.address.city || data.address.town || data.address.village || data.address.state || "Unknown"; locationDisplay.textContent = 📍 ${locationName}; localStorage.setItem("user_location", JSON.stringify({ name: locationName, lat: latitude, lon: longitude })); alert(Your Location:\n${locationName}\nLatitude: ${latitude}\nLongitude: ${longitude}); } catch (error) { console.error("Location name fetch failed:", error); alert(Coordinates:\nLat: ${latitude}\nLon: ${longitude}); } }, () => alert("Unable to retrieve your location.")); } else { alert("Geolocation not supported."); } });    
    
// === 3. Chat Modal === document.getElementById("customerCareBtn").addEventListener("click", () => { document.getElementById("chatModal").style.display = "block"; }); document.getElementById("chatCloseBtn").addEventListener("click", () => { document.getElementById("chatModal").style.display = "none"; }); document.getElementById("chatSendBtn").addEventListener("click", () => { const name = document.getElementById("chatName").value; const msg = document.getElementById("chatMessage").value; if (name && msg.trim()) { localStorage.setItem("chatMessageToAdmin", JSON.stringify({ name, msg })); alert("Message sent to admin!"); document.getElementById("chatMessage").value = ""; } else { alert("Enter your name and message."); } });    
    
// === 4. Orders Modal === document.getElementById("ordersBtn").addEventListener("click", () => { const modal = document.getElementById("ordersModal"); const content = document.getElementById("ordersContent"); const orders = JSON.parse(localStorage.getItem("orders")) || []; content.innerHTML = orders.length ? orders.map(order =>  <div class="order-card"> <p><strong>Order No:</strong> ${order.number}</p> <p><strong>Date:</strong> ${order.date}</p> <p><strong>Items:</strong> ${order.items.join(", ")}</p> <p><strong>Amount:</strong> ${order.amount}</p> <p><strong>Status:</strong> ${order.status}</p> <p><strong>Delivery:</strong> ${order.deliveryDate}</p> </div>).join("") : "<p>No orders yet.</p>"; modal.style.display = "block"; }); document.getElementById("ordersCloseBtn").addEventListener("click", () => { document.getElementById("ordersModal").style.display = "none"; });    
    
// === 5. Account Drop-down === const accountBtn = document.getElementById("accountBtn"); const dropdownMenu = document.querySelector(".dropdown-menu"); accountBtn.addEventListener("click", () => { dropdownMenu.classList.toggle("show"); });    
    
function updateAccountUI() { const user = JSON.parse(localStorage.getItem("user")); if (user) { dropdownMenu.innerHTML =  <div class="profile-summary"> <img src="${user.profilePhoto || 'default.jpg'}" alt="Profile" class="profile-pic"> <p>${user.username}</p> <p>${user.email}</p> <p>${user.contact}</p> <a href="#" id="logoutBtn">Logout</a> </div>; document.getElementById("logoutBtn").addEventListener("click", () => { localStorage.removeItem("user"); alert("Logged out!"); window.location.reload(); }); } else { dropdownMenu.innerHTML =  <a href="#" id="loginBtn">Login</a> <a href="#" id="registerBtn">Register</a> <a href="#" id="forgotPasswordBtn">Forgot Password?</a> <a href="#" id="settingsBtn">Settings</a>; document.getElementById("loginBtn").addEventListener("click", () => { document.getElementById("loginModal").style.display = "block"; }); document.getElementById("registerBtn").addEventListener("click", () => { document.getElementById("registerModal").style.display = "block"; }); document.getElementById("forgotPasswordBtn").addEventListener("click", () => { document.getElementById("forgotModal").style.display = "block"; }); } } updateAccountUI();    
    
// === 6. Login === document.getElementById("loginSubmitBtn").addEventListener("click", () => { const username = document.getElementById("loginUser").value; const password = document.getElementById("loginPass").value; if (username && password) { localStorage.setItem("user", JSON.stringify({ username, email: "user@example.com", contact: "+254700000000", profilePhoto: "profile.jpg" })); alert("Logged in!"); window.location.reload(); } else { alert("Enter both fields."); } });    
    
// === 7. Register === document.getElementById("registerSubmitBtn").addEventListener("click", () => { const username = document.getElementById("regUsername").value; const fullName = document.getElementById("regFullName").value; const email = document.getElementById("regEmail").value; const phone = document.getElementById("regPhone").value; const password = document.getElementById("regPass").value; const confirm = document.getElementById("regConfirm").value; if (!password.match(/^(?=.[a-zA-Z])(?=.\d)(?=.*[@#$%^&+=]).{6,}$/)) { return alert("Password must include letters, numbers & symbols."); } if (password !== confirm) return alert("Passwords don't match."); localStorage.setItem("user", JSON.stringify({ username, email, contact: phone, profilePhoto: "profile.jpg" })); alert("Registered!"); window.location.reload(); });    
    
// === 8. Forgot Password === document.getElementById("forgotSendBtn").addEventListener("click", () => { const contact = document.getElementById("forgotContact").value; if (contact) { const code = Math.floor(100000 + Math.random() * 900000); localStorage.setItem("resetCode", code); alert(6-digit code sent to ${contact}); } });    
    
document.getElementById("confirmCodeBtn").addEventListener("click", () => { const inputCode = document.getElementById("enteredCode").value; const savedCode = localStorage.getItem("resetCode"); if (inputCode === savedCode) { document.getElementById("resetStep2").style.display = "block"; } else { alert("Incorrect code."); } });    
    
document.getElementById("setNewPassBtn").addEventListener("click", () => { const pass1 = document.getElementById("newPass").value; const pass2 = document.getElementById("confirmNewPass").value; if (pass1 !== pass2) return alert("Passwords don't match"); alert("Password changed successfully."); });    
    
// === 9. Close All Modals === document.querySelectorAll(".closeBtn").forEach(btn => { btn.addEventListener("click", () => { btn.closest(".modal").style.display = "none"; }); }); });